language: cpp

os:
  - linux

env:
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=5
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=7

services:
  - docker

before_script:
  - echo DISTRIB=$DISTRIB
  - echo COMPILER_VERSION=$COMPILER_VERSION

script:
  - cd ${TRAVIS_BUILD_DIR}/docker
  - sed 's/DISTRIB_PLACEHOLDER/$DISTRIB/' Dockerfile-for-travis | docker build --build-arg COMPILER_VERSION=$COMPILER_VERSION --file - .
