language: cpp

os:
  - linux

env:
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=4.8 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=5 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=5 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=5 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=5 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=5 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=5 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=6 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=6 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=6 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=6 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=6 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=6 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=7 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=7 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=7 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=7 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=7 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=7 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=7 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=7 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=8 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=8 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=8 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=8 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=8 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=9 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:14.04 COMPILER_VERSION=9 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=9 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:16.04 COMPILER_VERSION=9 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=9 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=9 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=9 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=9 USE_INTERNAL_STL=no

  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=10 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:18.04 COMPILER_VERSION=10 USE_INTERNAL_STL=no
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=10 USE_INTERNAL_STL=yes
  - DISTRIB=ubuntu:20.04 COMPILER_VERSION=10 USE_INTERNAL_STL=no

services:
  - docker

before_script:
  - echo DISTRIB=$DISTRIB
  - echo COMPILER_VERSION=$COMPILER_VERSION
  - echo USE_INTERNAL_STL=$USE_INTERNAL_STL

script:
  - cd ${TRAVIS_BUILD_DIR}/docker
  - sed "s/DISTRIB_PLACEHOLDER/$DISTRIB/" Dockerfile-for-travis | docker build --build-arg COMPILER_VERSION=$COMPILER_VERSION --build-arg USE_INTERNAL_STL=$USE_INTERNAL_STL --file - .
