language: cpp

os:
  - linux

dist:
  - trusty
  - xenial
  - bionic

addons:
  apt:
    packages:
      - cmake
      - lua5.2

compiler:
  - gcc
  - clang

env:
  - USE_INTERNAL_STL=yes
  - USE_INTERNAL_STL=no

before_script:
    - mkdir ${TRAVIS_BUILD_DIR}/build
    - cd ${TRAVIS_BUILD_DIR}/build
script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_INTERNAL_STL=${USE_INTERNAL_STL} ${TRAVIS_BUILD_DIR}/src
    - cmake --build .
    - wget https://github.com/yandex/tomita-parser/releases/download/v1.0/libmystem_c_binding.so.linux_x64.zip
    - unzip libmystem_c_binding.so.linux_x64.zip
    - mv libmystem_c_binding.so ${TRAVIS_BUILD_DIR}/build/FactExtract/Parser/tomita-parser/
    - ctest

