language: cpp

os:
  - linux

jobs:
  include:
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-4.8 CXX=g++-4.8

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-4.8 CXX=g++-4.8

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-4.8 CXX=g++-4.8

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-4.8 CXX=g++-4.8

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-4.8 CXX=g++-4.8

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-4.8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-4.8 CXX=g++-4.8

    # focal: Package 'g++-4.8' has no installation candidate

    # GCC 5
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-5 CXX=g++-5

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=no CC=gcc-5 CXX=g++-5

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-5 CXX=g++-5

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=no CC=gcc-5 CXX=g++-5

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-5 CXX=g++-5

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-5']
      env:
        - USE_INTERNAL_STL=no CC=gcc-5 CXX=g++-5

    # focal: Package 'g++-5' has no installation candidate

    # GCC 6
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-6 CXX=g++-6

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=no CC=gcc-6 CXX=g++-6

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-6 CXX=g++-6

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=no CC=gcc-6 CXX=g++-6

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-6 CXX=g++-6

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-6']
      env:
        - USE_INTERNAL_STL=no CC=gcc-6 CXX=g++-6

    # focal: Package 'g++-6' has no installation candidate

    # GCC 7
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-7 CXX=g++-7

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=no CC=gcc-7 CXX=g++-7

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-7 CXX=g++-7

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=no CC=gcc-7 CXX=g++-7

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-7 CXX=g++-7

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=no CC=gcc-7 CXX=g++-7

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-7 CXX=g++-7

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-7']
      env:
        - USE_INTERNAL_STL=no CC=gcc-7 CXX=g++-7


    # GCC 8
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-8 CXX=g++-8

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-8 CXX=g++-8

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-8 CXX=g++-8

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-8 CXX=g++-8

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-8 CXX=g++-8

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-8 CXX=g++-8

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-8 CXX=g++-8

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-8']
      env:
        - USE_INTERNAL_STL=no CC=gcc-8 CXX=g++-8


    # GCC 9
    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-9 CXX=g++-9

    - dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=no CC=gcc-9 CXX=g++-9

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-9 CXX=g++-9

    - dist: xenial
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=no CC=gcc-9 CXX=g++-9

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-9 CXX=g++-9

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=no CC=gcc-9 CXX=g++-9

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-9 CXX=g++-9

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-9']
      env:
        - USE_INTERNAL_STL=no CC=gcc-9 CXX=g++-9


    # G++ 10

    # trusty, xenial: Couldn't find any package by regex 'g++-10'

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-10']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-10 CXX=g++-10

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-10']
      env:
        - USE_INTERNAL_STL=no CC=gcc-10 CXX=g++-10

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-10']
      env:
        - USE_INTERNAL_STL=yes CC=gcc-10 CXX=g++-10

    - dist: focal
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'lua5.2', 'g++-10']
      env:
        - USE_INTERNAL_STL=no CC=gcc-10 CXX=g++-10


before_script:
    - g++ --version
    - cmake --version
    - echo $PATH
    - cd ${TRAVIS_BUILD_DIR}
    - wget https://github.com/yandex/tomita-parser/releases/download/v1.0/libmystem_c_binding.so.linux_x64.zip
    - unzip libmystem_c_binding.so.linux_x64.zip
script:
    #    - mkdir ${TRAVIS_BUILD_DIR}/build_debug
    #    - cd ${TRAVIS_BUILD_DIR}/build_debug
    #    - cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_INTERNAL_STL=${USE_INTERNAL_STL} ${TRAVIS_BUILD_DIR}/src
    #    - cmake --build . -- VERBOSE=1
    #    - ln -s ${TRAVIS_BUILD_DIR}/libmystem_c_binding.so ${TRAVIS_BUILD_DIR}/build_debug/bin/libmystem_c_binding.so
    #    - ln -s ${TRAVIS_BUILD_DIR}/libmystem_c_binding.so ${TRAVIS_BUILD_DIR}/build_debug/FactExtract/Parser/tomita-parser/libmystem_c_binding.so
    #    - cd ../examples/bornin/ && ../../build_debug/bin/tomita-parser config.proto
    #    - cd ${TRAVIS_BUILD_DIR}/build_debug
    #    - ctest -VV
    - mkdir ${TRAVIS_BUILD_DIR}/build_release
    - cd ${TRAVIS_BUILD_DIR}/build_release
    - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_INTERNAL_STL=${USE_INTERNAL_STL} -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=false ${TRAVIS_BUILD_DIR}/src
    - cmake --build . -- VERBOSE=1
    - ln -s ${TRAVIS_BUILD_DIR}/libmystem_c_binding.so ${TRAVIS_BUILD_DIR}/build_release/bin/libmystem_c_binding.so
    - ln -s ${TRAVIS_BUILD_DIR}/libmystem_c_binding.so ${TRAVIS_BUILD_DIR}/build_release/FactExtract/Parser/tomita-parser/libmystem_c_binding.so
    - ldd bin/tomita-parser
    - file FactExtract/Parser/tomita-parser/tomita-parser
    - cd ../examples/bornin/ && ../../build_release/bin/tomita-parser config.proto
    - cd ${TRAVIS_BUILD_DIR}/build_release
    - ctest -VV

